mqtt:
  server: "mqtts://mqtt-broker:8883" # Conexión TLS al puerto seguro
  user: "" # Dejar vacío si no usas autenticación
  password: ""
  topic_path: "central_node/decisions"
  qos: 1
  client_id: "mqtt2prometheus-exporter"
  ca_cert: "/certs/ca.crt"
  client_cert: "/certs/server.crt"
  client_key: "/certs/server.key"
